name : Publish Package to Composer
on :
  release :
    types : [ published ]
jobs :
  publish :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v3
      - uses : shivammathur/setup-php@v2
        with :
          php-version : '8.3'
          tools : composer:v2
      - run : composer install
      - run : ./vendor/bin/pest --group=continuous-integration
